services:
    Imaximius\WorkflowBundle\Metadata\Resource\Factory\WorkflowOperationResourceMetadataFactory:
        decorates: 'api_platform.metadata.resource.metadata_factory'
        arguments:
            - '@Imaximius\WorkflowBundle\Metadata\Resource\Factory\WorkflowOperationResourceMetadataFactory.inner'
            - [ ]

    Imaximius\WorkflowBundle\PathResolver\OperationPathResolver:
        decorates: 'api_platform.operation_path_resolver.generator'
        arguments:
            - '@Imaximius\WorkflowBundle\PathResolver\OperationPathResolver.inner'

    Imaximius\WorkflowBundle\EventListener\WorkflowStateListener:
        tags:
            - { name: 'doctrine.event_subscriber' }
        arguments:
            - '@Symfony\Component\Workflow\Registry'
            - [ ]

    Imaximius\WorkflowBundle\EventListener\WorkflowEnabledTransitionsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 21 }